openapi: 3.1.0
info:
  title: conversation-api
  version: ${memovee_ui_version}

servers:
  - url: ${memovee_ui_endpoint}

paths:
  /conversation/messages/{message_id}/artifacts:
    post:
      operationId: create-message-artifact
      summary: Create message artifact
      description: Creates a new artifact for a message.
      parameters:
        - name: message_id
          in: path
          required: true
          schema:
            type: string
          description: ID of the message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/artifact-request"
      responses:
        "201":
          description: Artifact created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/artifact-response"
              examples:
                success:
                  summary: Example response
                  value:
                    data:
                      id: "some-id"
        "400":
          description: Bad Request – invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error-response"
              examples:
                invalidType:
                  summary: Invalid type provided
                  value:
                    error: "Invalid 'type' field. Must be 'list' or 'detail'."
                missingField:
                  summary: Missing required field
                  value:
                    error: "Request body must include 'type'."

components:
  schemas:
    artifact-request:
      title: artifact-request
      description: Request body for creating or retrieving message artifacts.
      type: object
      properties:
        type:
          type: string
          enum: [list, detail]
          description: The mode of retrieval, either a list of artifacts or detailed information.
        index:
          type: integer
          description: Index order of the artifact to that will be displayed. Lower number shows first higher number shows later.
        items:
          type: array
          description: List of artifact identifiers.
          items:
            type: string
        properties:
          type: array
          description: List of properties with their relevance scores.
          items:
            type: object
            properties:
              name:
                type: string
                description: Property name.
              relevance:
                type: integer
                description: Relevance score for this property.
      required:
        - type

    artifact-response:
      title: artifact-response
      description: Response body when an artifact is successfully created.
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier of the created artifact.
          required:
            - id
      required:
        - data

    error-response:
      title: error-response
      description: Standard error response returned when a request is invalid.
      type: object
      properties:
        error:
          type: string
          description: Description of the error that occurred.
      required:
        - error
